; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Mon Apr 05 2021 20:54:33 GMT+0200 (Central European Summer Time)

